### ISSUE TITLE
Unable to resole symbol __imp_glewInit on Win10

### ISSUE THREAD

**Issue by wzjing** [ArthurSonzogni/OpenGL_CMake_Skeleton#4]
- OS: Win10
- Cmake: 3.13
- Toolchain: MSCV
- IDE: CLion

**ISSUE:** Unable to resolve glew functions:
```
Application.cpp.obj : error LNK2019: Unable to resole symbol __imp_glewInit
```
**SOLUTION:** From [GLEW](http://glew.sourceforge.net/install.html):
```
cmake_minimum_required(VERSION 3.1)
project(opengl-skeleton)

if (WIN32)
    add_definitions(-DGLEW_STATIC)
endif ()

...
```

Hope this could be add to repo!

**Comment by ArthurSonzogni** [comment]
Thanks! I uploaded a fix.
